### ISSUE TITLE
node_modules folder have to be in .gitignore file 

### ISSUE THREAD

**Issue by emredoganm** [serhatYilmazz/blockchain#1]
Your repository will be bigger when **node_modules** folder has been added to the repository. You already have **package-lock.json** file due to detecting the repository's dependencies and their versions. I mean you **_should add_** **node_modules** folder to your .**gitignore** file.

**Comment by emredoganm** [comment]
Additionally, it is important to keep your git commit history clean. When you would add a package in the future to the repository, your commit history will not be limited only with **package.json** update.

You can look at this article: https://flaviocopes.com/should-commit-node-modules-git/

**Comment by serhatYilmazz** [comment]
Thank you. Issue is resolved it was my bad.
